/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import javax.swing.JOptionPane;
import config.MyConfig;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {

    public void clear() {
        Input_Nama.setText("");
        Input_Harga.setText("");
        Input_Jumlah.setText("");
        Label_Nama.requestFocus();
    }
    
    public void insertData(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getRowCount();
        model.addRow(new Object[]{
            row += 1,
            Input_Nama.getText(),
            Input_Harga.getText(),
            Input_Jumlah.getText(),
        });
    }
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Label_Nama = new javax.swing.JLabel();
        Label_Harga = new javax.swing.JLabel();
        Label_Jumlah = new javax.swing.JLabel();
        Input_Nama = new javax.swing.JTextField();
        Input_Harga = new javax.swing.JTextField();
        Input_Jumlah = new javax.swing.JTextField();
        Btn_Add = new javax.swing.JButton();
        Btn_Edit = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        Btn_Clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Label_Total = new javax.swing.JLabel();
        Label_Tunai = new javax.swing.JLabel();
        Label_Kembali = new javax.swing.JLabel();
        Btn_Hitung = new javax.swing.JButton();
        Btn_Simpan = new javax.swing.JButton();
        Input_Total = new javax.swing.JTextField();
        Input_Tunai = new javax.swing.JTextField();
        Input_Kembali = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Title.setBackground(java.awt.Color.black);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Database App ");

        javax.swing.GroupLayout Panel_TitleLayout = new javax.swing.GroupLayout(Panel_Title);
        Panel_Title.setLayout(Panel_TitleLayout);
        Panel_TitleLayout.setHorizontalGroup(
            Panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TitleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_TitleLayout.setVerticalGroup(
            Panel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TitleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Label_Nama.setText("Nama");

        Label_Harga.setText("Harga");

        Label_Jumlah.setText("Jumlah");

        Input_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_NamaActionPerformed(evt);
            }
        });

        Input_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_HargaActionPerformed(evt);
            }
        });

        Btn_Add.setText("Tambah");
        Btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddActionPerformed(evt);
            }
        });

        Btn_Edit.setText("Edit");
        Btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditActionPerformed(evt);
            }
        });

        Btn_Delete.setText("Delete");
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        Btn_Clear.setText("Clear");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        Label_Total.setText("Total ");

        Label_Tunai.setText("Tunai");

        Label_Kembali.setText("Kembali");

        Btn_Hitung.setText("Hitung");
        Btn_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HitungActionPerformed(evt);
            }
        });

        Btn_Simpan.setText("Simpan ke Database");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });

        Input_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_TotalActionPerformed(evt);
            }
        });

        Input_Tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_TunaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Btn_Hitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(Btn_Simpan)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Input_Tunai, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Tunai)
                            .addComponent(Label_Kembali)
                            .addComponent(Label_Total))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Input_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Input_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Total)
                    .addComponent(Input_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Tunai)
                    .addComponent(Input_Tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Kembali)
                    .addComponent(Input_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Hitung)
                    .addComponent(Btn_Simpan))
                .addGap(25, 25, 25))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Harga", "Jumlah"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Input_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Label_Jumlah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label_Nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label_Harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Input_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(Input_Jumlah)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(Btn_Add)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Edit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Delete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_Clear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Nama)
                            .addComponent(Input_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Harga)
                            .addComponent(Input_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Jumlah)
                            .addComponent(Input_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Add)
                            .addComponent(Btn_Edit)
                            .addComponent(Btn_Delete)
                            .addComponent(Btn_Clear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_HargaActionPerformed

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int jumlahRowData = jTable1.getRowCount();
        
        if (jumlahRowData == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak tersedia");
        } else {
           
            for (int i=0; i<jumlahRowData; i++) {
                String namaBarang = model.getValueAt(i, 1).toString();
                int hargaBarang = Integer.parseInt(model.getValueAt(i, 2).toString());
                int jumlahBarang = Integer.parseInt(model.getValueAt(i, 3).toString());
                
                MyConfig.insertData(namaBarang, hargaBarang, jumlahBarang);
            }
        }
        model.setRowCount(0);
        Input_Total.setText("");
        Input_Tunai.setText("");
        Input_Kembali.setText("");
        JOptionPane.showMessageDialog(null, "Data Tersimpan ke database");
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Input_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_TotalActionPerformed

    private void Btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddActionPerformed
        // TODO add your handling code here:
        if (Label_Nama.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama barang belum di input");
        } else if (Label_Harga.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga barang belum di input");
        } else if (Label_Jumlah.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah Barang belum di input");
        }else {
            insertData();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
            clear();
        }
    }//GEN-LAST:event_Btn_AddActionPerformed

    private void Input_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_NamaActionPerformed

    private void Btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditActionPerformed
        // TODO add your handling code here:
        int indexDataSelect = jTable1.getSelectedRow();
        int jumlahRowData = jTable1.getRowCount();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        
        if (jumlahRowData == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak tersedia");
        } else {
            if (indexDataSelect != -1) {
                if (Btn_Edit.getText().equals("Edit")){
                Btn_Add.setEnabled(false);
                Btn_Edit.setText("Update");
                Btn_Delete.setEnabled(false);
                
                Input_Nama.setText(model.getValueAt(indexDataSelect,1).toString());
                Input_Harga.setText(model.getValueAt(indexDataSelect,2).toString());
                Input_Jumlah.setText(model.getValueAt(indexDataSelect,3).toString());
            } else {
                Btn_Add.setEnabled(true);
                Btn_Edit.setText("Edit");
                Btn_Delete.setEnabled(true);
                
                model.setValueAt(Input_Nama.getText().toString(), indexDataSelect, 1);
                model.setValueAt(Input_Harga.getText().toString(), indexDataSelect, 2);
                model.setValueAt(Input_Jumlah.getText().toString(), indexDataSelect, 3);
        
                clear();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin diedit");
            }
        }
    }//GEN-LAST:event_Btn_EditActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int indexDataSelect = jTable1.getSelectedRow();
        int jumlahRowData = jTable1.getRowCount();
        
        if (jumlahRowData == 0) {
            JOptionPane.showMessageDialog(null, "Data tidak tersedia");
        } else {
            if (indexDataSelect != -1) {
                model.removeRow(indexDataSelect);
            } else {
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
            }
        }
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void Btn_HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HitungActionPerformed
        // TODO add your handling code here:    
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int jumlahRowData = jTable1.getRowCount();
        
        int totalHarga = 0;
        int inputTunai = 0;
        
        for (int i=0; i<jumlahRowData; i++) {
            int hargaBarang = Integer.parseInt(model.getValueAt(i, 2).toString());
            int jumlahBarang = Integer.parseInt(model.getValueAt(i, 3).toString());
            
            int subTotal = hargaBarang * jumlahBarang;
            totalHarga +=subTotal;
        }
        
        String tunai = Input_Tunai.getText();
        if (!tunai.isEmpty()) {
            try {
                inputTunai = Integer.parseInt(tunai);
            } catch (NumberFormatException e) {
                String total = String.valueOf(totalHarga);
                Input_Total.setText(total);
                JOptionPane.showMessageDialog(null, "Inputan tidak valid. Masukkan angka!");
                return;
            }
        } else {
            String total = String.valueOf(totalHarga);
            Input_Total.setText(total);
            JOptionPane.showMessageDialog(null, "Inputan kosong. Masukkan angka!");
            return;
        }
        
        String total = String.valueOf(totalHarga);
        Input_Total.setText(total);
        
        if (inputTunai < totalHarga) {
            JOptionPane.showMessageDialog(null, "Nilai tunai harus lebih besar atau sama dengan total harga!");
            Input_Kembali.setText("");
        } else {
            int kembalian = inputTunai - totalHarga;
            String kembali = String.valueOf(kembalian);
            Input_Kembali.setText(kembali);
            JOptionPane.showMessageDialog(null, "Berhasil menghitung");
        }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        clear();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:        
    }//GEN-LAST:event_Btn_HitungActionPerformed

    private void Input_TunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_TunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_TunaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Add;
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_Edit;
    private javax.swing.JButton Btn_Hitung;
    private javax.swing.JButton Btn_Simpan;
    private javax.swing.JTextField Input_Harga;
    private javax.swing.JTextField Input_Jumlah;
    private javax.swing.JTextField Input_Kembali;
    private javax.swing.JTextField Input_Nama;
    private javax.swing.JTextField Input_Total;
    private javax.swing.JTextField Input_Tunai;
    private javax.swing.JLabel Label_Harga;
    private javax.swing.JLabel Label_Jumlah;
    private javax.swing.JLabel Label_Kembali;
    private javax.swing.JLabel Label_Nama;
    private javax.swing.JLabel Label_Total;
    private javax.swing.JLabel Label_Tunai;
    private javax.swing.JPanel Panel_Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
